#!/bin/bash
# Create pull request for issue
# Environment variables required:
#   - GH_TOKEN
#   - ISSUE_NUMBER
#   - ISSUE_TITLE
#   - ISSUE_BODY
# Usage: create-pr.sh <branch_name> <default_branch>

set -euo pipefail

BRANCH_NAME="${1:-}"
DEFAULT_BRANCH="${2:-main}"

if [ -z "$BRANCH_NAME" ]; then
  echo "::error::Branch name is required"
  exit 1
fi

if [ -z "${GH_TOKEN:-}" ]; then
  echo "::error::GH_TOKEN is not set"
  exit 1
fi

if [ -z "${ISSUE_NUMBER:-}" ] || [ -z "${ISSUE_TITLE:-}" ] || [ -z "${ISSUE_BODY:-}" ]; then
  echo "::error::Issue information is incomplete"
  exit 1
fi

echo "::group::🔍 Checking for existing PR"

# Check if PR already exists for this branch
# Try multiple methods to check for existing PR, as gh pr view might fail due to permissions
EXISTING_PR=""
PR_NUMBER=""
PR_STATE=""
PR_URL=""

# Method 1: Try gh pr view (most reliable if permissions allow)
set +e  # Temporarily disable exit on error
EXISTING_PR=$(gh pr view "$BRANCH_NAME" --json number,url,state 2>&1)
VIEW_EXIT_CODE=$?
set -e  # Re-enable exit on error

if [ $VIEW_EXIT_CODE -eq 0 ] && [ -n "$EXISTING_PR" ]; then
  # Successfully got PR info
  PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.number // empty' 2>/dev/null || echo "")
  PR_STATE=$(echo "$EXISTING_PR" | jq -r '.state // empty' 2>/dev/null || echo "")
  PR_URL=$(echo "$EXISTING_PR" | jq -r '.url // empty' 2>/dev/null || echo "")
  
  if [ -n "$PR_NUMBER" ]; then
    echo "✅ Pull request already exists: #$PR_NUMBER ($PR_STATE)"
    echo "🔗 $PR_URL"
    echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
    echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
    echo "pr_exists=true" >> "$GITHUB_OUTPUT"
    echo "::endgroup::"
    exit 0
  fi
fi

# Method 2: Try gh pr list as fallback (might have different permission requirements)
if [ -z "$PR_NUMBER" ]; then
  set +e
  PR_LIST=$(gh pr list --head "$BRANCH_NAME" --json number,url,state --limit 1 2>&1)
  LIST_EXIT_CODE=$?
  set -e
  
  if [ $LIST_EXIT_CODE -eq 0 ] && [ -n "$PR_LIST" ]; then
    PR_COUNT=$(echo "$PR_LIST" | jq 'length' 2>/dev/null || echo "0")
    if [ "$PR_COUNT" -gt 0 ]; then
      PR_NUMBER=$(echo "$PR_LIST" | jq -r '.[0].number // empty' 2>/dev/null || echo "")
      PR_STATE=$(echo "$PR_LIST" | jq -r '.[0].state // empty' 2>/dev/null || echo "")
      PR_URL=$(echo "$PR_LIST" | jq -r '.[0].url // empty' 2>/dev/null || echo "")
      
      if [ -n "$PR_NUMBER" ]; then
        echo "✅ Pull request already exists: #$PR_NUMBER ($PR_STATE)"
        echo "🔗 $PR_URL"
        echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
        echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
        echo "pr_exists=true" >> "$GITHUB_OUTPUT"
        echo "::endgroup::"
        exit 0
      fi
    fi
  fi
fi

# If both methods failed, check if it's a permission error
# If it's a permission error and we can't check, we should still try to create
# (it might succeed if the PR doesn't exist, or fail with a clear error if it does)
if echo "$EXISTING_PR" | grep -qiE "not accessible|permission|unauthorized"; then
  echo "⚠️  Cannot check for existing PR due to permissions, will attempt to create"
  echo "ℹ️  If PR already exists, creation will fail with a clear error"
else
  echo "ℹ️  No existing PR found"
fi
echo "::endgroup::"

echo "::group::📝 Creating Pull Request"

# Prepare PR details safely using environment variables to prevent script injection
PR_TITLE_FILE=$(mktemp)
PR_BODY_FILE=$(mktemp)
trap 'rm -f "$PR_TITLE_FILE" "$PR_BODY_FILE"' EXIT

# Safely construct PR title using environment variable (already escaped)
printf '🤖 Automated PR for Issue #%s: %s' "${ISSUE_NUMBER}" "${ISSUE_TITLE}" > "$PR_TITLE_FILE"

# Safely construct PR body using environment variable
cat > "$PR_BODY_FILE" <<PRBODY
This PR was automatically generated by the AI Coder agent.

Closes #${ISSUE_NUMBER}

---
**Issue Context:**

${ISSUE_BODY}
PRBODY

# Read from files to safely pass to gh CLI (prevents command injection)
PR_TITLE=$(cat "$PR_TITLE_FILE")
PR_BODY=$(cat "$PR_BODY_FILE")

# Create pull request using GitHub CLI
# First try with label, if label doesn't exist, create without label
PR_RESULT=$(gh pr create \
  --base "$DEFAULT_BRANCH" \
  --head "$BRANCH_NAME" \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --label "🤖ai:generated" 2>&1) || {
  PR_CREATE_EXIT_CODE=$?
  ERROR_OUTPUT="$PR_RESULT"
  
  # Check error type
  if echo "$ERROR_OUTPUT" | grep -qiE "label.*not found|could not add label"; then
    # Label doesn't exist, retry without label
    echo "::warning::Label 'ai-generated' not found, creating PR without label"
    PR_RESULT=$(gh pr create \
      --base "$DEFAULT_BRANCH" \
      --head "$BRANCH_NAME" \
      --title "$PR_TITLE" \
      --body "$PR_BODY" 2>&1) || {
      ERROR_OUTPUT="$PR_RESULT"
      echo "::error::Failed to create pull request (without label)"
      echo "Exit code: $?"
      echo "Error output:"
      echo "$ERROR_OUTPUT"
      echo "pr_exists=error" >> "$GITHUB_OUTPUT"
      exit 1
    }
    else
      # Check if PR was actually created despite the error
      # Sometimes gh pr create succeeds but returns error due to permission issues (e.g., adding label)
      # Verify by checking if PR actually exists
      echo "⚠️  Error occurred, but checking if PR was actually created..."
      
      set +e
      EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number,url,state --limit 1 2>&1)
      LIST_EXIT_CODE=$?
      set -e
      
      if [ $LIST_EXIT_CODE -eq 0 ] && [ -n "$EXISTING_PR" ]; then
        PR_COUNT=$(echo "$EXISTING_PR" | jq 'length' 2>/dev/null || echo "0")
        if [ "$PR_COUNT" -gt 0 ]; then
          PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.[0].number // empty' 2>/dev/null || echo "")
          PR_URL=$(echo "$EXISTING_PR" | jq -r '.[0].url // empty' 2>/dev/null || echo "")
          PR_STATE=$(echo "$EXISTING_PR" | jq -r '.[0].state // empty' 2>/dev/null || echo "")
          
          if [ -n "$PR_NUMBER" ]; then
            echo "✅ Pull request was created successfully: #$PR_NUMBER ($PR_STATE)"
            echo "🔗 $PR_URL"
            echo "ℹ️  Ignoring permission error (PR creation succeeded)"
            echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
            echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
            echo "pr_exists=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi
      fi
      
      # Check if error indicates PR already exists
      if echo "$PR_RESULT" | grep -qiE "already exists|already.*pull request|pull request.*already"; then
        echo "ℹ️  Pull request already exists for this branch"
        echo "Attempting to retrieve PR details..."
        
        if [ -n "$EXISTING_PR" ] && [ "$PR_COUNT" -gt 0 ]; then
          PR_NUMBER=$(echo "$EXISTING_PR" | jq -r '.[0].number // empty' 2>/dev/null || echo "")
          PR_URL=$(echo "$EXISTING_PR" | jq -r '.[0].url // empty' 2>/dev/null || echo "")
          PR_STATE=$(echo "$EXISTING_PR" | jq -r '.[0].state // empty' 2>/dev/null || echo "")
          
          if [ -n "$PR_NUMBER" ]; then
            echo "✅ Found existing PR: #$PR_NUMBER ($PR_STATE)"
            echo "🔗 $PR_URL"
            echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
            echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
            echo "pr_exists=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
        fi
        
        echo "⚠️  PR exists but could not retrieve details"
        echo "pr_exists=true" >> "$GITHUB_OUTPUT"
        exit 0
      else
        # Real error - PR was not created
        echo "::error::Failed to create pull request"
        echo "Exit code: $PR_CREATE_EXIT_CODE"
        echo "Error output:"
        echo "$PR_RESULT"
        echo "pr_exists=error" >> "$GITHUB_OUTPUT"
        exit 1
      fi
    fi
}

# Extract PR URL and number from result
PR_URL=$(echo "$PR_RESULT" | grep -o 'https://github.com/[^ ]*' | head -1 || echo "")
PR_NUMBER=$(echo "$PR_URL" | grep -o '/pull/[0-9]*' | grep -o '[0-9]*' || echo "")

if [ -n "$PR_URL" ] && [ -n "$PR_NUMBER" ]; then
  echo "✅ Pull request created successfully"
  echo "🔗 $PR_URL"
  echo "pr_number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
  echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
  echo "pr_exists=false" >> "$GITHUB_OUTPUT"
else
  echo "::error::Failed to extract PR information from result"
  echo "PR result: $PR_RESULT"
  echo "pr_exists=error" >> "$GITHUB_OUTPUT"
  exit 1
fi

echo "::endgroup::"
