const axios = require('axios');

async function askAI(prompt, model = "anthropic/claude-3.5-sonnet") {
  const res = await axios.post('https://openrouter.ai/api/v1/chat/completions', {
    model: model,
    messages: [{ role: "user", content: prompt }]
  }, {
    headers: {
      'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
      'HTTP-Referer': 'https://github.com/vibe-kanban'
    }
  });
  return res.data.choices[0].message.content;
}

if (process.env.EVENT_CONTEXT === 'issues') {
  const issue = context.payload.issue;
  const prompt = `[Vibe Mode: Spec Generation]
  需求：${issue.title} - ${issue.body}
  作为全栈专家，请按照 Context, Backend (Go), Frontend (Next.js), Checklist 结构给出简洁的技术接力卡片。`;
  
  const response = await askAI(prompt);
  await github.rest.issues.createComment({
    ...context.repo,
    issue_number: issue.number,
    body: `## 🌊 Vibe Relay Card\n\n${response}\n\n--- \n*Generated by OpenRouter AI*`
  });

} else if (process.env.EVENT_CONTEXT === 'pull_request') {
  const pr = context.payload.pull_request;
  const { data: diff } = await github.rest.pulls.get({
    ...context.repo,
    pull_number: pr.number,
    mediaType: { format: 'diff' }
  });

  const prompt = `[Vibe Mode: Night Watch]
  分析此 Go/Next.js 的 diff。
  给出 Vibe Score (1-10)，指出 Critical Fixes 和 1 个优化建议。
  Diff: ${diff.slice(0, 4000)}`;

  const response = await askAI(prompt);
  await github.rest.issues.createComment({
    ...context.repo,
    issue_number: pr.number,
    body: `### 🛡️ AI Guard Report\n\n${response}`
  });
}
