export interface VideoMetadata {
  videoId: string;
  title: string;
  author: string;
  thumbnailUrl: string;
  duration: number;
  description?: string;
  isCached?: boolean;
}

export interface YoutubeMetadata extends VideoMetadata {
  thumbnails: Record<string, any>;
}

export interface PlaylistVideo {
  videoId: string;
  title: string;
  thumbnailUrl: string;
  position: number;
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

// New structured transcript types
export interface TranscriptSegment {
  start: string;
  end: string;
  text: string;
}

export interface VideoInfo {
  name: string;
  thumbnailUrl: {
    hqdefault: string;
    maxresdefault: string;
  };
  embedUrl: string;
  duration: string;
  description: string;
  upload_date: string;
  genre: string;
  author: string;
  channel_id: string;
}

export interface LanguageCode {
  code: string;
  name: string;
}

export interface TranscriptData {
  custom: TranscriptSegment[];
  default: TranscriptSegment[];
  auto: TranscriptSegment[];
}

export interface CaptionsResponse {
  videoId: string;
  videoInfo: VideoInfo;
  language_code: LanguageCode[];
  transcripts: Record<string, TranscriptData>;
}

export interface QuotaStatus {
  remaining: number;
  total: number;
  percent: number;
}

export interface Chapter {
  title: string;
  timestamp: string;
  seconds: number;
}

export interface TranscriptItem {
  text: string;
  timestamp: string;
  seconds: number;
}

export interface AnalysisResult {
  analysisId?: number;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  summary?: string;
  keyPoints?: string[];
  chapters?: Chapter[];
  transcription?: TranscriptItem[];
}

export interface HistoryItem {
  videoId: string;
  title: string;
  thumbnailUrl: string;
  createdAt: string;
}
