export interface VideoMetadata {
  videoId: string;
  title: string;
  author: string;
  thumbnailUrl: string;
  duration: number;
  description?: string;
  isCached?: boolean;
}

export interface YoutubeMetadata extends VideoMetadata {
  thumbnails: Record<string, any>;
}

export interface PlaylistVideo {
  videoId: string;
  title: string;
  thumbnailUrl: string;
  position: number;
}

export interface CaptionTrack {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

export interface QuotaStatus {
  remaining: number;
  total: number;
  percent: number;
}

export interface Chapter {
  title: string;
  timestamp: string;
  seconds: number;
}

export interface TranscriptItem {
  text: string;
  timestamp: string;
  seconds: number;
}

export interface AnalysisResult {
  status: 'pending' | 'processing' | 'completed' | 'failed';
  summary?: string;
  keyPoints?: string[];
  chapters?: Chapter[];
  transcription?: TranscriptItem[];
}

export interface HistoryItem {
  videoId: string;
  title: string;
  thumbnailUrl: string;
  createdAt: string;
}